services:
  mongo:
    image: 'mongo:3'
    volumes:
      - mongo-data:/data/db
    networks:
      - central-network
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.6.11'
    ports:
      - '9200:9200'
      - '9300:9300'
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - central-network
  graylog:
    image: 'graylog/graylog:2.4.6-1'
    env_file:
      - .env
    ports:
      - '9000:9000'
      - '12201:12201'
      - '514:514'
      - '5555:5555'
    networks:
      - central-network
volumes:
  mongo-data:
  es-data:
networks:
  central-network:
    name: central-network
    driver: bridge